[formatter.nixfmt-rfc-style]
command = "nixfmt"
includes = ["*.nix"]

[formatter.ormolu]
command = "ormolu"
options = ["--mode", "inplace"]
includes = ["*.hs", "**/*.hs"]

[formatter.prettier]
command = "prettier"
options = ["--write"]
includes = ["*.html", "**/*.html"]
